config/routes.rb
Phone::Application.routes.draw do
  root :to => 'home#index'
  devise_for :users
  resources :numbers
  resources :calls do
    member do
      get 'toggle_new'
    end
  end
  resources :contacts
  resources :scripts do
    resources :items
  end
  resources :mailboxes do
    resources :messages
  end
  match 'api' =>               'api#index'
  match 'api/call' =>          'api#call'
  match 'api/menu' =>          'api#menu'
  match 'api/info' =>          'api#info'
  match 'api/music' =>         'api#music'
  match 'api/music/songs' =>   'api#songs'
  match 'api/music/artists' => 'api#artists'
  match 'api/play' =>          'api#play'
  match 'api/message' =>       'api#message'
  match 'api/messages' =>      'api#messages'
  match 'api/mailbox' =>       'api#mailbox'
  resources :music
end

app/models/script.rb
class Script < ActiveRecord::Base
  attr_accessible :name

  has_many :items

  def to_s
    name
  end
end

app/controllers/scripts_controller.rb
class ScriptsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @scripts = Script.all
  end

  def new
    @script = Script.new
  end

  def edit
    @script = Script.find(params[:id])
  end

  def show
    @script = Script.find(params[:id])
    @items = @script.items

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @script }
      format.xml { render :action => "show.xml.builder", :layout => false }
    end
  end

  def update
    @script = Script.find(params[:id])

    respond_to do |format|
      if @script.update_attributes(params[:script])
        format.html { redirect_to scripts_path, notice: 'Script was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @script.errors, status: :unprocessable_entity }
      end
    end
  end

  def create
    @script = Script.new(params[:script])

    respond_to do |format|
      if @script.save
        format.html { redirect_to scripts_path, notice: 'Script was successfully created.' }
        format.json { render json: @script, status: :created, location: @script }
      else
        format.html { render action: "new" }
        format.json { render json: @script.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @script = Script.find(params[:id])
    @script.destroy

    respond_to do |format|
      format.html { redirect_to scripts_url }
      format.json { head :no_content }
    end
  end
end

app/views/scripts/_form.html.erb
<%= form_for(@script) do |f| %>
  <% if @script.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@script.errors.count, "error") %> prohibited this script from being saved:</h2>

      <ul>
      <% @script.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scripts/index.html.erb
<%= link_to 'New', new_script_path, :class => "btn" %>
<br><br>

<table class="table table-striped">
  <% @scripts.each do |script| %>
    <tr>
      <td><%= link_to script.name, script %></td>
      <td><%= link_to 'Edit', edit_script_path(script) %></td>
      <td><%= link_to 'Destroy', script, confirm: 'Are you sure?', method: :delete %></td>
    </tr>
  <% end %>
</table>

app/views/scripts/new.html.erb
<h1>New Script</h1>

<%= render 'form' %>

app/views/scripts/show.html.erb
<div><%= @script.name %></div>