config/routes.rb
Phone::Application.routes.draw do
  root :to => 'home#index'
  devise_for :users
  resources :numbers
  resources :calls do
    member do
      get 'toggle_new'
    end
  end
  resources :contacts
  resources :scripts do
    resources :items
  end
  resources :mailboxes do
    resources :messages
  end
  match 'api' =>               'api#index'
  match 'api/call' =>          'api#call'
  match 'api/menu' =>          'api#menu'
  match 'api/info' =>          'api#info'
  match 'api/music' =>         'api#music'
  match 'api/music/songs' =>   'api#songs'
  match 'api/music/artists' => 'api#artists'
  match 'api/play' =>          'api#play'
  match 'api/message' =>       'api#message'
  match 'api/messages' =>      'api#messages'
  match 'api/mailbox' =>       'api#mailbox'
  resources :music
end

app/models/number.rb
class Number < ActiveRecord::Base
  attr_accessible :number, :name, :script_id, :user_id, :verified
  belongs_to :script
  belongs_to :user

  def to_s
    name
  end
end

app/controllers/numbers_controller.rb
class NumbersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @numbers = current_user.numbers.all(:order => "name")
  end

  def edit
    @number = current_user.numbers.find(params[:id])
  end

  def new
    @number = current_user.numbers.new
  end

  def create
    @number = current_user.numbers.new(params[:number])

    respond_to do |format|
      if @number.save
        format.html { redirect_to numbers_path, notice: 'Number was successfully created.' }
        format.json { render json: @number, status: :created, location: @number }
      else
        format.html { render action: "new" }
        format.json { render json: @number.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @number = current_user.numbers.find(params[:id])

    respond_to do |format|
      if @number.update_attributes(params[:number])
        format.html { redirect_to numbers_path, notice: 'Number was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @number.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/views/numbers/_form.html.erb
<%= form_for(@number) do |f| %>
  <% if @number.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@number.errors.count, "error") %> prohibited this number from being saved:</h2>

      <ul>
      <% @number.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :number %>
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :script_id %>
    <%= select("number", "script_id", Script.all.collect {|p| [ p.name, p.id ] }, {:include_blank => 'None'}) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/numbers/edit.html.erb
<div><%= @number.name %></div>
<div><%= @number.number %></div>

app/views/numbers/index.html.erb
<%= link_to 'New', new_number_path, :class => "btn" %>
<br><br>

<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Script</th>
    <th>Number</th>
    <th></th>
  </tr>
  <% @numbers.each do |number| %>
    <tr>
      <td><%= number.name %></td>
      <td><%= number.script %></td>
      <td><%= number.number %></td>
      <td><%= link_to "Edit", edit_number_path(number) %></td>
    </tr>
  <% end %>
</table>

app/views/numbers/new.html.erb
<h1>New Number</h1>

<%= render 'form' %>