config/routes.rb
Phone::Application.routes.draw do
  root :to => 'home#index'
  devise_for :users
  resources :numbers
  resources :calls do
    member do
      get 'toggle_new'
    end
  end
  resources :contacts
  resources :scripts do
    resources :items
  end
  resources :mailboxes do
    resources :messages
  end
  match 'api' =>               'api#index'
  match 'api/call' =>          'api#call'
  match 'api/menu' =>          'api#menu'
  match 'api/info' =>          'api#info'
  match 'api/music' =>         'api#music'
  match 'api/music/songs' =>   'api#songs'
  match 'api/music/artists' => 'api#artists'
  match 'api/play' =>          'api#play'
  match 'api/message' =>       'api#message'
  match 'api/messages' =>      'api#messages'
  match 'api/mailbox' =>       'api#mailbox'
  resources :music
end

app/models/mailbox.rb
class Mailbox < ActiveRecord::Base
  attr_accessible :name, :user_id

  belongs_to :user
  has_many :messages

  def new_messages
    messages.where("new = ?", true)
  end

  def saved_messages
    messages.where("new = ?", false)
  end
end

app/controllers/mailboxes_controller.rb
class MailboxesController < ApplicationController
  before_filter :authenticate_user!

  def base
    #if current_user.admin
    #  Mailbox
    #else
      current_user.mailboxes
    #end
  end

  def index
    @mailboxes = base.all
  end

  def new
    @mailbox = current_user.mailboxes.new
  end

  def edit
    @mailbox = base.find(params[:id])
  end

  def show
    @mailbox = base.find(params[:id])
    @messages = @mailbox.messages.all
  end

  def create
    @mailbox = current_user.mailboxes.new(params[:mailbox])
    if @mailbox.save
      redirect_to mailboxes_path
    else
      render :action => "new"
    end
  end

  def update
    @mailbox = base.find(params[:id])
    if @mailbox.update_attributes(params[:mailbox])
      redirect_to mailboxes_path
    else
      render :action => "edit"
    end
  end

  def destroy
    @mailbox = base.find(params[:id])
    @mailbox.delete
    redirect_to mailboxes_path
  end
end

app/views/mailboxes/_form.html.erb
<%= form_for(@mailbox) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mailboxes/index.html.erb
<%= link_to "New", new_mailbox_path, class: "btn" %>
<br><br>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Messages</th>
    <th></th>
    <th></th>
  </tr>
  <% @mailboxes.each do |mailbox| %>
    <tr>
      <td><%= link_to mailbox.name, mailbox %></td>
      <td><span class="badge"><%= mailbox.messages.count %></span></td>
      <td><%= link_to "Edit", edit_mailbox_path(mailbox) %></td>
      <td><%= link_to "Delete", mailbox, confirm: 'Are you sure?', method: :delete %></td>
    </tr>
  <% end %>
</table>

app/views/mailboxes/new.html.erb
<%= render 'form' %>

app/views/mailboxes/show.html.erb
<h1><%= @mailbox.name %></h1>
<table class="table table-striped">
  <tr>
    <th></th>
    <th>Date</th>
    <th>Caller</th>
    <th></th>
    <th></th>
  </tr>
  <% @messages.each do |message| %>
  <tr>
    <td><%= message_badge(message) %></td>
    <td><%= to_pst(message.created_at) %></td>
    <td><%= caller_name(message) %></td>
    <td>
        <audio controls preload="none">
            <source src="<%= message.url %>" type="audio/mp3" />
            Your browser does not support the audio tag. <a href="<%= message.url %>">Listen</a>
        </audio>
    </td>
    <td><%= link_to "", [@mailbox, message], confirm: 'Are you sure?', method: :delete, class: "icon-trash" %></td>
  </tr>
  <% end %>
</table>