config/routes.rb
Phone::Application.routes.draw do
  root :to => 'home#index'
  devise_for :users
  resources :numbers
  resources :calls do
    member do
      get 'toggle_new'
    end
  end
  resources :contacts
  resources :scripts do
    resources :items
  end
  resources :mailboxes do
    resources :messages
  end
  match 'api' =>               'api#index'
  match 'api/call' =>          'api#call'
  match 'api/menu' =>          'api#menu'
  match 'api/info' =>          'api#info'
  match 'api/music' =>         'api#music'
  match 'api/music/songs' =>   'api#songs'
  match 'api/music/artists' => 'api#artists'
  match 'api/play' =>          'api#play'
  match 'api/message' =>       'api#message'
  match 'api/messages' =>      'api#messages'
  match 'api/mailbox' =>       'api#mailbox'
  resources :music
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Slit</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="container">
      <ul class="nav nav-pills pull-right">
        <li><a href="http://git.jbussdieker.com">Git</a></li>
        <li><a href="http://blog.jbussdieker.com">Blog</a></li>
        <li><a href="http://wiki.jbussdieker.com">Wiki</a></li>
        <li class="active"><a href="/">Phone</a></li>
      </ul>
    </div>
    <div class="navbar">
      <div class="navbar-inner">
        <div class="container">
          <div class="nav-collapse">
            <ul class="nav">
              <li class="<%= 'active' if params[:controller] == 'home' %>">
                <%= link_to 'Home', "/" %>
              </li>
              <% if user_signed_in? %>
                <li class="<%= 'active' if params[:controller] == 'contacts' %>">
                  <%= link_to 'Contacts', contacts_path %>
                </li>
                <li class="<%= 'active' if params[:controller] == 'mailboxes' %>">
                  <%= link_to 'Mailboxes', mailboxes_path %>
                </li>
                <li class="<%= 'active' if params[:controller] == 'numbers' %>">
                  <%= link_to 'Numbers', numbers_path %>
                </li>
                <li class="<%= 'active' if params[:controller] == 'calls' %>">
                  <%= link_to 'Calls', calls_path %>
                </li>
                <li class="<%= 'active' if params[:controller].starts_with? 'music' %>">
                  <%= link_to 'Music', "/music" %>
                </li>
                <li class="<%= 'active' if params[:controller] == 'scripts' %>">
                  <%= link_to 'Scripts', scripts_path %>
                </li>
              <% else %>
                <li>
                  <%= link_to('Login', new_user_session_path) %>
                </li>
              <% end %>
            </ul>
          </div>
          <% if user_signed_in? %>
          <div class="btn-group pull-right">
            <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
              <i class="icon-user"></i> <%= current_user.email %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to('Profile', edit_user_registration_path) %></li>
              <li class="divider"></li>
              <li><%= link_to('Sign Out', destroy_user_session_path, :method => :delete) %></li>
            </ul>
          </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="container">
      <% flash.each do |name, msg| %>
        <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
          <a class="close" data-dismiss="alert">&#215;</a>
          <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </div>
</body>
</html>